<Project>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">

    <AnalysisLevel>10-recommended</AnalysisLevel>
    <AnalysisLevelSecurity>10-all</AnalysisLevelSecurity>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RunAnalyzers>true</RunAnalyzers>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <OptimizeImplicitlyTriggeredBuild>false</OptimizeImplicitlyTriggeredBuild>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>

  </PropertyGroup>

</Project>
