<Project>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.Analyzers.props" />

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
