using System.Text.Json.Serialization;

namespace CodigoActivo.Domain.Entities;

/// <summary>
/// Identifies the second factor a user must present after the password.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<TwoFactorMethod>))]
public enum TwoFactorMethod
{
    /// <summary>
    /// A one-time code is emailed to the account address on every login.
    /// </summary>
    Email = 1,

    /// <summary>
    /// A time-based one-time password generated by an authenticator application.
    /// </summary>
    Authenticator = 2,
}
