using System.ComponentModel.DataAnnotations;
using CodigoActivo.Application.Validation;
using CodigoActivo.Domain.Entities;

namespace CodigoActivo.Application.DTOs;

/// <summary>
/// Contains the client-supplied data used to login.
/// </summary>
/// <param name="Identifier">Email address of the account.</param>
/// <param name="Password">Plain-text password to hash or verify.</param>
public record LoginRequest(
    [Required] [MaxLength(256)] [NotBlank] string Identifier,
    [Required] [MaxLength(128)] [NotBlank] string Password
);

/// <summary>
/// Contains the pending second-factor challenge data returned by the API after the password step.
/// </summary>
/// <param name="Method">Second factor the user must present.</param>
/// <param name="MaskedEmail">
/// Partially hidden address the code was emailed to; <see langword="null"/> for authenticators.
/// </param>
public record LoginChallengeResponse(TwoFactorMethod Method, string? MaskedEmail);

/// <summary>
/// Contains the client-supplied data used to complete a login with the second factor.
/// </summary>
/// <param name="Code">Code from the email or the authenticator application.</param>
/// <param name="KeepSignedIn">
/// Whether the user explicitly asked to stay signed in on this device; only then does the session
/// cookie outlive the browser session.
/// </param>
public record TwoFactorLoginRequest(
    [Required] [MaxLength(16)] [NotBlank] string Code,
    bool KeepSignedIn = false
);

/// <summary>
/// Contains the client-supplied data used to start enrolling an authenticator application.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the change.</param>
public record AuthenticatorSetupRequest(
    [Required] [MaxLength(128)] [NotBlank] string CurrentPassword
);

/// <summary>
/// Contains the authenticator enrollment data returned by the API.
/// </summary>
/// <param name="SharedKey">Shared secret in groups of four characters, for manual entry.</param>
/// <param name="AuthenticatorUri">The otpauth URI encoded in the QR code.</param>
public record AuthenticatorSetupResponse(string SharedKey, string AuthenticatorUri);

/// <summary>
/// Contains the client-supplied data used to confirm an authenticator enrollment.
/// </summary>
/// <param name="Code">First code generated by the authenticator application.</param>
public record ConfirmAuthenticatorRequest([Required] [MaxLength(16)] [NotBlank] string Code);

/// <summary>
/// Contains the client-supplied data used to return to email as the second factor.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the change.</param>
/// <param name="Code">Current code of the authenticator being removed.</param>
public record DisableAuthenticatorRequest(
    [Required] [MaxLength(128)] [NotBlank] string CurrentPassword,
    [Required] [MaxLength(16)] [NotBlank] string Code
);

/// <summary>
/// Contains the csrf token data returned by the API.
/// </summary>
/// <param name="Token">The token value.</param>
/// <param name="HeaderName">The header name value.</param>
public record CsrfTokenResponse(string Token, string HeaderName);

/// <summary>
/// Contains the client-supplied data used to register.
/// </summary>
/// <param name="FirstName">User's given name.</param>
/// <param name="LastName">User's family name.</param>
/// <param name="Email">Email address to validate or locate.</param>
/// <param name="Phone">Phone number to validate or locate.</param>
/// <param name="Password">Plain-text password to hash or verify.</param>
/// <param name="NationalId">
/// Spanish DNI or NIE of the adult. Not unique, so registering never reveals whether another
/// account already uses it.
/// </param>
/// <param name="Gender">The gender value.</param>
/// <param name="PromotionalConsent">Whether the adult agrees to receive promotional content.</param>
/// <param name="Minors">The minors value.</param>
/// <param name="SecondaryPhone">
/// Optional second contact phone of the adult; blank means none and it must differ from
/// <paramref name="Phone"/>.
/// </param>
public record RegisterRequest(
    [Required] [MaxLength(120)] [NotBlank] string FirstName,
    [Required] [MaxLength(120)] [NotBlank] string LastName,
    [Required] [EmailAddress] [MaxLength(256)] string Email,
    [Required] [Phone] [MaxLength(40)] string Phone,
    [Required] [MinLength(12)] [MaxLength(128)] [NotBlank] string Password,
    [Required] [MaxLength(12)] [NotBlank] [SpanishNationalId] string NationalId,
    [EnumDataType(typeof(Gender))] Gender Gender,
    bool PromotionalConsent,
    [MaxLength(20)] IReadOnlyList<RegisterMinorRequest>? Minors,
    [Phone] [MaxLength(40)] string? SecondaryPhone = null
);

/// <summary>
/// Contains the client-supplied data used to register minor.
/// </summary>
/// <param name="FirstName">User's given name.</param>
/// <param name="LastName">User's family name.</param>
/// <param name="BirthDate">User's date of birth.</param>
/// <param name="Gender">The gender value.</param>
public record RegisterMinorRequest(
    [Required] [MaxLength(120)] [NotBlank] string FirstName,
    [Required] [MaxLength(120)] [NotBlank] string LastName,
    [NotDefaultOrFutureDate] DateOnly BirthDate,
    [EnumDataType(typeof(Gender))] Gender Gender
);

/// <summary>
/// Contains the register data returned by the API.
/// </summary>
/// <param name="Adult">The adult value, pending until the emailed verification link is opened.</param>
/// <param name="Minors">The minors value.</param>
public record RegisterResponse(UserResponse Adult, IReadOnlyList<UserResponse> Minors);

/// <summary>
/// Contains the client-supplied data used to verify.
/// </summary>
/// <param name="Otp">The otp value.</param>
public record VerifyRequest([Required] [MaxLength(128)] [NotBlank] string Otp);

/// <summary>
/// Contains the client-supplied data used to forgot password.
/// </summary>
/// <param name="Email">Email address to validate or locate.</param>
public record ForgotPasswordRequest([Required] [EmailAddress] [MaxLength(256)] string Email);

/// <summary>
/// Contains the client-supplied data used to reset password.
/// </summary>
/// <param name="Otp">The otp value.</param>
/// <param name="NewPassword">The new password value.</param>
public record ResetPasswordRequest(
    [Required] [MaxLength(128)] [NotBlank] string Otp,
    [Required] [MinLength(12)] [MaxLength(128)] [NotBlank] string NewPassword
);
