using System.ComponentModel.DataAnnotations;
using CodigoActivo.Application.Accounts.Commands;
using CodigoActivo.Application.Common.Mapping;
using CodigoActivo.Application.Users.Commands;
using CodigoActivo.Application.Users.Contracts;
using CodigoActivo.Domain.Users;
using Gender = CodigoActivo.Application.Users.Contracts.Gender;

namespace CodigoActivo.API.Accounts.Contracts;

/// <summary>
/// Contains the client-supplied data used to login.
/// </summary>
/// <param name="Identifier">Email address of the account.</param>
/// <param name="Password">Plain-text password to hash or verify.</param>
public record LoginRequest(
    [Required] [MaxLength(256)] string Identifier,
    [Required] [MaxLength(128)] string Password
)
{
    /// <summary>
    /// Builds the command that checks the password.
    /// </summary>
    /// <returns>The command.</returns>
    public LoginCommand ToCommand()
    {
        return new LoginCommand(Identifier, Password);
    }
}

/// <summary>
/// Contains the client-supplied data used to complete a login with the second factor.
/// </summary>
/// <param name="Code">Code from the email or the authenticator application.</param>
/// <param name="KeepSignedIn">
/// Whether the user explicitly asked to stay signed in on this device; only then does the session
/// cookie outlive the browser session.
/// </param>
public record TwoFactorLoginRequest(
    [Required] [MaxLength(16)] string Code,
    bool KeepSignedIn = false
);

/// <summary>
/// Contains the client-supplied data used to start enrolling an authenticator application.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the change.</param>
public record AuthenticatorSetupRequest([Required] [MaxLength(128)] string CurrentPassword)
{
    /// <summary>
    /// Builds the command that starts the enrollment.
    /// </summary>
    /// <returns>The command.</returns>
    public BeginAuthenticatorSetupCommand ToCommand()
    {
        return new BeginAuthenticatorSetupCommand(CurrentPassword);
    }
}

/// <summary>
/// Contains the client-supplied data used to confirm an authenticator enrollment.
/// </summary>
/// <param name="Code">First code generated by the authenticator application.</param>
public record ConfirmAuthenticatorRequest([Required] [MaxLength(16)] string Code)
{
    /// <summary>
    /// Builds the command that confirms the enrollment.
    /// </summary>
    /// <returns>The command.</returns>
    public ConfirmAuthenticatorCommand ToCommand()
    {
        return new ConfirmAuthenticatorCommand(Code);
    }
}

/// <summary>
/// Contains the client-supplied data used to return to email as the second factor.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the change.</param>
/// <param name="Code">Current code of the authenticator being removed.</param>
public record DisableAuthenticatorRequest(
    [Required] [MaxLength(128)] string CurrentPassword,
    [Required] [MaxLength(16)] string Code
)
{
    /// <summary>
    /// Builds the command that removes the authenticator.
    /// </summary>
    /// <returns>The command.</returns>
    public DisableAuthenticatorCommand ToCommand()
    {
        return new DisableAuthenticatorCommand(CurrentPassword, Code);
    }
}

/// <summary>
/// Contains the client-supplied data used to register.
/// </summary>
/// <param name="FirstName">User's given name.</param>
/// <param name="LastName">User's family name.</param>
/// <param name="Email">Email address to validate or locate.</param>
/// <param name="Phone">Phone number to validate or locate.</param>
/// <param name="Password">Plain-text password to hash or verify.</param>
/// <param name="NationalId">
/// Spanish DNI or NIE of the adult. Not unique, so registering never reveals whether another
/// account already uses it.
/// </param>
/// <param name="Gender">The gender value.</param>
/// <param name="PromotionalConsent">Whether the adult agrees to receive promotional content.</param>
/// <param name="Minors">The minors value.</param>
/// <param name="SecondaryPhone">
/// Optional second contact phone of the adult; blank means none and it must differ from
/// <paramref name="Phone"/>.
/// </param>
public record RegisterRequest(
    [Required] [MaxLength(120)] string FirstName,
    [Required] [MaxLength(120)] string LastName,
    [Required] [EmailAddress] [MaxLength(256)] string Email,
    [Required] [MaxLength(40)] string Phone,
    [Required] [MinLength(12)] [MaxLength(128)] string Password,
    [Required] [MaxLength(12)] string NationalId,
    [EnumDataType(typeof(Gender))] Gender Gender,
    bool PromotionalConsent,
    [MaxLength(Household.MaxDependents)] IReadOnlyList<RegisterMinorRequest>? Minors,
    [MaxLength(40)] string? SecondaryPhone = null
)
{
    /// <summary>
    /// Builds the command that registers the household.
    /// </summary>
    /// <returns>The command.</returns>
    public RegisterCommand ToCommand()
    {
        return new RegisterCommand(
            FirstName,
            LastName,
            Email,
            Phone,
            Password,
            NationalId,
            Gender.ToDomain(),
            PromotionalConsent,
            [.. (Minors ?? []).Select(minor => minor.ToDraft())],
            SecondaryPhone
        );
    }
}

/// <summary>
/// Contains the client-supplied data used to register minor.
/// </summary>
/// <param name="FirstName">User's given name.</param>
/// <param name="LastName">User's family name.</param>
/// <param name="BirthDate">User's date of birth.</param>
/// <param name="Gender">The gender value.</param>
public record RegisterMinorRequest(
    [Required] [MaxLength(120)] string FirstName,
    [Required] [MaxLength(120)] string LastName,
    DateOnly BirthDate,
    [EnumDataType(typeof(Gender))] Gender Gender
)
{
    /// <summary>
    /// Gets the details of the minor.
    /// </summary>
    /// <returns>The details.</returns>
    public MinorDraft ToDraft()
    {
        return new MinorDraft(FirstName, LastName, BirthDate, Gender.ToDomain());
    }
}

/// <summary>
/// Contains the client-supplied data used to verify.
/// </summary>
/// <param name="Otp">The otp value.</param>
public record VerifyRequest([Required] [MaxLength(128)] string Otp);

/// <summary>
/// Contains the client-supplied data used to forgot password.
/// </summary>
/// <param name="Email">Email address to validate or locate.</param>
public record ForgotPasswordRequest([Required] [EmailAddress] [MaxLength(256)] string Email)
{
    /// <summary>
    /// Builds the command that emails a reset code.
    /// </summary>
    /// <returns>The command.</returns>
    public ForgotPasswordCommand ToCommand()
    {
        return new ForgotPasswordCommand(Email);
    }
}

/// <summary>
/// Contains the client-supplied data used to send a new verification link.
/// </summary>
/// <param name="Email">Email of the account that waits for verification.</param>
public record ResendVerificationRequest([Required] [EmailAddress] [MaxLength(256)] string Email)
{
    /// <summary>
    /// Builds the command that sends a new verification link.
    /// </summary>
    /// <returns>The command.</returns>
    public ResendVerificationCommand ToCommand()
    {
        return new ResendVerificationCommand(Email);
    }
}

/// <summary>
/// Contains the client-supplied data used to reset password.
/// </summary>
/// <param name="Otp">The otp value.</param>
/// <param name="NewPassword">The new password value.</param>
public record ResetPasswordRequest(
    [Required] [MaxLength(128)] string Otp,
    [Required] [MinLength(12)] [MaxLength(128)] string NewPassword
)
{
    /// <summary>
    /// Builds the command that resets the password.
    /// </summary>
    /// <param name="userId">Identifier of the account.</param>
    /// <returns>The command.</returns>
    public ResetPasswordCommand ToCommand(UserId userId)
    {
        return new ResetPasswordCommand(userId, Otp, NewPassword);
    }
}

/// <summary>
/// Contains the client-supplied data used to request the code that confirms account deletion.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the request.</param>
public record AccountDeletionCodeRequest([Required] [MaxLength(128)] string CurrentPassword)
{
    /// <summary>
    /// Builds the command that emails the deletion code.
    /// </summary>
    /// <returns>The command.</returns>
    public RequestAccountDeletionCodeCommand ToCommand()
    {
        return new RequestAccountDeletionCodeCommand(CurrentPassword);
    }
}

/// <summary>
/// Contains the client-supplied data used to delete the signed-in user's own account.
/// </summary>
/// <param name="CurrentPassword">Password of the signed-in user, re-entered to authorize the deletion.</param>
/// <param name="Code">Code from the email or the authenticator application.</param>
public record DeleteAccountRequest(
    [Required] [MaxLength(128)] string CurrentPassword,
    [Required] [MaxLength(16)] string Code
)
{
    /// <summary>
    /// Builds the command that deletes the account.
    /// </summary>
    /// <returns>The command.</returns>
    public DeleteOwnAccountCommand ToCommand()
    {
        return new DeleteOwnAccountCommand(CurrentPassword, Code);
    }
}

/// <summary>
/// Contains the client-supplied data used to change password.
/// </summary>
/// <param name="CurrentPassword">The current password value.</param>
/// <param name="NewPassword">The new password value.</param>
public record ChangePasswordRequest(
    [Required] [MaxLength(128)] string CurrentPassword,
    [Required] [MinLength(12)] [MaxLength(128)] string NewPassword
)
{
    /// <summary>
    /// Builds the command that changes the password.
    /// </summary>
    /// <param name="userId">Identifier of the account.</param>
    /// <returns>The command.</returns>
    public ChangePasswordCommand ToCommand(UserId userId)
    {
        return new ChangePasswordCommand(userId, CurrentPassword, NewPassword);
    }
}
