namespace CodigoActivo.Application.Abstractions.Security;

/// <summary>
/// Hashes and verifies the random one-time codes the application emails: login and account deletion
/// codes and the tokens of account links. They are short-lived and generated by the server, so they
/// need a keyed hash that a copy of the database cannot test guesses against, not the memory-hard
/// work of a password hash.
/// </summary>
public interface IOneTimeCodeHasher
{
    /// <summary>
    /// Hashes a code for storage.
    /// </summary>
    /// <param name="code">Code to hash.</param>
    /// <returns>The encoded hash.</returns>
    public string Hash(string code);

    /// <summary>
    /// Verifies a code against a hash produced by <see cref="Hash"/>.
    /// </summary>
    /// <param name="code">Code to verify.</param>
    /// <param name="hash">Encoded hash of the stored code.</param>
    /// <returns><see langword="true"/> when the code matches; otherwise, <see langword="false"/>.</returns>
    public bool Verify(string code, string hash);
}
