// <auto-generated />
using System;
using CodigoActivo.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodigoActivo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CodigoActivoDbContext))]
    [Migration("20260711113952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivityEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_ends_at");

                    b.Property<Guid>("ActivityModalityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_modality_type_id");

                    b.Property<DateTimeOffset>("ActivityStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_starts_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ActivityModalityTypeId")
                        .HasDatabaseName("ix_activities_activity_modality_type_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_activities_created_by");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_activities_event_id");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_activities_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_activities_updated_by");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityModalityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activity_modality_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_modality_types_name");

                    b.ToTable("activity_modality_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityRoleCapacity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("ActivityRoleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_role_type_id");

                    b.Property<int>("DesiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("desired_count");

                    b.HasKey("ActivityId", "ActivityRoleTypeId")
                        .HasName("pk_activity_role_capacities");

                    b.HasIndex("ActivityRoleTypeId")
                        .HasDatabaseName("ix_activity_role_capacities_activity_role_type_id");

                    b.ToTable("activity_role_capacities", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activity_role_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_role_types_name");

                    b.ToTable("activity_role_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityUserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("ActivityRoleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_role_type_id");

                    b.Property<Guid>("AssignmentStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_status_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ActivityId", "ActivityRoleTypeId")
                        .HasName("pk_activity_user_role_assignments");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_activity_user_role_assignments_activity_id");

                    b.HasIndex("ActivityRoleTypeId")
                        .HasDatabaseName("ix_activity_user_role_assignments_activity_role_type_id");

                    b.HasIndex("AssignmentStatusId")
                        .HasDatabaseName("ix_activity_user_role_assignments_assignment_status_id");

                    b.ToTable("activity_user_role_assignments", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_announcements_created_by");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_announcements_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_announcements_updated_by");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.AssignmentStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_assignment_status_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_status_types_name");

                    b.ToTable("assignment_status_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EventEndsAt")
                        .HasColumnType("date")
                        .HasColumnName("event_ends_at");

                    b.Property<DateOnly>("EventStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("event_starts_at");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured");

                    b.Property<DateTimeOffset>("SignupEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_ends_at");

                    b.Property<DateTimeOffset>("SignupStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_starts_at");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_events_created_by");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_events_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_events_updated_by");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.EventCategory", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("EventCategoryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_category_type_id");

                    b.HasKey("EventId", "EventCategoryTypeId")
                        .HasName("pk_event_categories");

                    b.HasIndex("EventCategoryTypeId")
                        .HasDatabaseName("ix_event_categories_event_category_type_id");

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.EventCategoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_event_category_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_event_category_types_name");

                    b.ToTable("event_category_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_files_uploaded_by");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_partners_created_by");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_partners_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_partners_updated_by");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_type_id");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_resources_created_by");

                    b.HasIndex("ResourceTypeId")
                        .HasDatabaseName("ix_resources_resource_type_id");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_resources_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_resources_updated_by");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_external");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_types_name");

                    b.ToTable("resource_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OtpCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("otp_code_hash");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<DateTimeOffset?>("OtpLastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_last_sent_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<DateTimeOffset?>("PasswordResetLastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_last_sent_at");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserStatusTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_status_type_id");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_type_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_users_parent_id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("UserStatusTypeId")
                        .HasDatabaseName("ix_users_user_status_type_id");

                    b.HasIndex("UserTypeId")
                        .HasDatabaseName("ix_users_user_type_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.UserStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_status_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_status_types_name");

                    b.ToTable("user_status_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_types_name");

                    b.ToTable("user_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Activity", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.ActivityModalityType", "ActivityModalityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityModalityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_activity_modality_types_activity_modality_type_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_events_event_id");

                    b.HasOne("CodigoActivo.Domain.Entities.FileEntity", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activities_users_updated_by");

                    b.Navigation("ActivityModalityType");

                    b.Navigation("Event");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityRoleCapacity", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.Activity", "Activity")
                        .WithMany("RoleCapacities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_role_capacities_activities_activity_id");

                    b.HasOne("CodigoActivo.Domain.Entities.ActivityRoleType", "ActivityRoleType")
                        .WithMany()
                        .HasForeignKey("ActivityRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_role_capacities_activity_role_types_activity_role_");

                    b.Navigation("Activity");

                    b.Navigation("ActivityRoleType");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityUserRoleAssignment", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.Activity", "Activity")
                        .WithMany("Assignments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_user_role_assignments_activities_activity_id");

                    b.HasOne("CodigoActivo.Domain.Entities.ActivityRoleType", "ActivityRoleType")
                        .WithMany("Assignments")
                        .HasForeignKey("ActivityRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_user_role_assignments_activity_role_types_activity");

                    b.HasOne("CodigoActivo.Domain.Entities.AssignmentStatusType", "AssignmentStatus")
                        .WithMany("Assignments")
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_user_role_assignments_assignment_status_types_assi");

                    b.HasOne("CodigoActivo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_user_role_assignments_users_user_id");

                    b.Navigation("Activity");

                    b.Navigation("ActivityRoleType");

                    b.Navigation("AssignmentStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_announcements_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Entities.FileEntity", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_announcements_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_announcements_users_updated_by");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Event", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Entities.FileEntity", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_users_updated_by");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.EventCategory", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.EventCategoryType", "EventCategoryType")
                        .WithMany("Events")
                        .HasForeignKey("EventCategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_event_category_types_event_category_type_id");

                    b.HasOne("CodigoActivo.Domain.Entities.Event", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_events_event_id");

                    b.Navigation("Event");

                    b.Navigation("EventCategoryType");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_users_uploaded_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Partner", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Entities.FileEntity", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_partners_users_updated_by");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Resource", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Entities.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_resource_types_resource_type_id");

                    b.HasOne("CodigoActivo.Domain.Entities.FileEntity", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resources_users_updated_by");

                    b.Navigation("ResourceType");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.User", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Entities.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_users_users_parent_id");

                    b.HasOne("CodigoActivo.Domain.Entities.UserStatusType", "UserStatusType")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_status_types_user_status_type_id");

                    b.HasOne("CodigoActivo.Domain.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_types_user_type_id");

                    b.Navigation("Parent");

                    b.Navigation("UserStatusType");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RoleCapacities");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityModalityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ActivityRoleType", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.AssignmentStatusType", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.Event", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.EventCategoryType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.User", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.UserStatusType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
