// <auto-generated />
using System;
using CodigoActivo.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodigoActivo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CodigoActivoDbContext))]
    partial class CodigoActivoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodigoActivo.Domain.Activities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActivityEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_ends_at");

                    b.Property<Guid>("ActivityModalityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_modality_type_id");

                    b.Property<DateTimeOffset>("ActivityStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_starts_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("ActivityModalityTypeId")
                        .HasDatabaseName("ix_activities_activity_modality_type_id");

                    b.HasIndex("ActivityStartsAt")
                        .HasDatabaseName("ix_activities_activity_starts_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_activities_created_by");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_activities_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_activities_updated_by");

                    b.HasIndex("EventId", "ActivityStartsAt")
                        .HasDatabaseName("ix_activities_event_id_activity_starts_at");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.ActivityModalityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activity_modality_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_modality_types_name");

                    b.ToTable("activity_modality_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.ActivityRoleCapacity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("ActivityRoleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_role_type_id");

                    b.Property<int>("DesiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("desired_count");

                    b.HasKey("ActivityId", "ActivityRoleTypeId")
                        .HasName("pk_activity_role_capacities");

                    b.HasIndex("ActivityRoleTypeId")
                        .HasDatabaseName("ix_activity_role_capacities_activity_role_type_id");

                    b.ToTable("activity_role_capacities", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.ActivityRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activity_role_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_activity_role_types_name");

                    b.ToTable("activity_role_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.Assignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("ActivityRoleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_role_type_id");

                    b.Property<Guid>("AssignmentStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_status_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ActivityId", "ActivityRoleTypeId")
                        .HasName("pk_assignments");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_assignments_activity_id");

                    b.HasIndex("ActivityRoleTypeId")
                        .HasDatabaseName("ix_assignments_activity_role_type_id");

                    b.HasIndex("AssignmentStatusId")
                        .HasDatabaseName("ix_assignments_assignment_status_id");

                    b.HasIndex("UserId", "ActivityId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_user_id_activity_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.AssignmentStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_assignment_status_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_status_types_name");

                    b.ToTable("assignment_status_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.EventCategories.EventCategoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_event_category_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_event_category_types_name");

                    b.ToTable("event_category_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EarlySignupStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("early_signup_starts_at");

                    b.Property<DateOnly>("EventEndsAt")
                        .HasColumnType("date")
                        .HasColumnName("event_ends_at");

                    b.Property<DateOnly>("EventStartsAt")
                        .HasColumnType("date")
                        .HasColumnName("event_starts_at");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<DateTimeOffset>("SignupEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_ends_at");

                    b.Property<DateTimeOffset>("SignupStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signup_starts_at");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_events_created_by");

                    b.HasIndex("EventEndsAt")
                        .HasDatabaseName("ix_events_event_ends_at");

                    b.HasIndex("EventStartsAt")
                        .HasDatabaseName("ix_events_event_starts_at");

                    b.HasIndex("Featured")
                        .IsUnique()
                        .HasDatabaseName("ix_events_featured")
                        .HasFilter("featured");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_events_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_events_updated_by");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventCategory", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("EventCategoryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_category_type_id");

                    b.HasKey("EventId", "EventCategoryTypeId")
                        .HasName("pk_event_categories");

                    b.HasIndex("EventCategoryTypeId")
                        .HasDatabaseName("ix_event_categories_event_category_type_id");

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LeastLiked")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("least_liked");

                    b.Property<string>("MostLiked")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("most_liked");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Suggestions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("suggestions");

                    b.HasKey("Id")
                        .HasName("pk_event_ratings");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_ratings_event_id");

                    b.ToTable("event_ratings", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventTermsAcceptance", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TermsDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("terms_document_id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.HasKey("EventId", "UserId", "TermsDocumentId")
                        .HasName("pk_event_terms_acceptances");

                    b.HasIndex("TermsDocumentId")
                        .HasDatabaseName("ix_event_terms_acceptances_terms_document_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_terms_acceptances_user_id");

                    b.ToTable("event_terms_acceptances", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventTermsDocument", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("TermsDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("terms_document_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("EventId", "TermsDocumentId")
                        .HasName("pk_event_terms_documents");

                    b.HasIndex("TermsDocumentId")
                        .HasDatabaseName("ix_event_terms_documents_terms_document_id");

                    b.ToTable("event_terms_documents", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_files_uploaded_by");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.News.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_news");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_news_created_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_news_created_by");

                    b.HasIndex("Featured")
                        .IsUnique()
                        .HasDatabaseName("ix_news_featured")
                        .HasFilter("featured");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_news_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_news_updated_by");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Web")
                        .HasColumnType("text")
                        .HasColumnName("web");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_partners_created_by");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_partners_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_partners_updated_by");

                    b.HasIndex("Tier", "FromDate")
                        .HasDatabaseName("ix_partners_tier_from_date");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_type_id");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("ThumbnailId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_resources_created_at");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_resources_created_by");

                    b.HasIndex("ResourceTypeId")
                        .HasDatabaseName("ix_resources_resource_type_id");

                    b.HasIndex("ThumbnailId")
                        .HasDatabaseName("ix_resources_thumbnail_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_resources_updated_by");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Resources.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_external");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_types_name");

                    b.ToTable("resource_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.TermsDocuments.TermsDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_terms_documents");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_terms_documents_name");

                    b.ToTable("terms_documents", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.DeletedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.HasKey("Id")
                        .HasName("pk_deleted_accounts");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_deleted_accounts_deleted_at");

                    b.ToTable("deleted_accounts", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticatorKey")
                        .HasColumnType("text")
                        .HasColumnName("authenticator_key");

                    b.Property<long?>("AuthenticatorLastUsedStep")
                        .HasColumnType("bigint")
                        .HasColumnName("authenticator_last_used_step");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LoginChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_challenge_id");

                    b.Property<DateTimeOffset?>("LoginCodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_code_expires_at");

                    b.Property<string>("LoginCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("login_code_hash");

                    b.Property<DateTimeOffset?>("LoginCodeLastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_code_last_sent_at");

                    b.Property<string>("NationalId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("national_id");

                    b.Property<string>("OtpCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("otp_code_hash");

                    b.Property<DateTimeOffset?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<DateTimeOffset?>("OtpLastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_last_sent_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("PasswordFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("password_failed_attempts");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("PasswordLockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_locked_at");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<DateTimeOffset?>("PasswordResetLastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_last_sent_at");

                    b.Property<DateTimeOffset?>("PendingAuthenticatorExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_authenticator_expires_at");

                    b.Property<string>("PendingAuthenticatorKey")
                        .HasColumnType("text")
                        .HasColumnName("pending_authenticator_key");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<bool>("PromotionalConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("promotional_consent");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("text")
                        .HasColumnName("secondary_phone");

                    b.Property<int>("TwoFactorFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("two_factor_failed_attempts");

                    b.Property<DateTimeOffset?>("TwoFactorLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_factor_locked_until");

                    b.Property<string>("TwoFactorMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("two_factor_method");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserStatusTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_status_type_id");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_type_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_users_parent_id");

                    b.HasIndex("UserStatusTypeId")
                        .HasDatabaseName("ix_users_user_status_type_id");

                    b.HasIndex("UserTypeId")
                        .HasDatabaseName("ix_users_user_type_id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("ix_users_first_name_last_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.UserStatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_status_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_status_types_name");

                    b.ToTable("user_status_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_types_name");

                    b.ToTable("user_types", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.DisposableEmailDomain", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.HasKey("Domain")
                        .HasName("pk_disposable_email_domains");

                    b.ToTable("disposable_email_domains", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("html_body");

                    b.Property<byte[]>("Subject")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("subject");

                    b.Property<byte[]>("TextBody")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("text_body");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox_contents");

                    b.ToTable("email_outbox_contents", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxContentPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disposition");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("InlineContentId")
                        .HasColumnType("text")
                        .HasColumnName("inline_content_id");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox_content_parts");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_email_outbox_content_parts_content_id");

                    b.ToTable("email_outbox_content_parts", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_address");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_name");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox_messages");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_email_outbox_messages_content_id");

                    b.HasIndex("Priority", "NextAttemptAt")
                        .HasDatabaseName("ix_email_outbox_messages_priority_next_attempt_at");

                    b.ToTable("email_outbox_messages", (string)null);
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.Activity", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Activities.ActivityModalityType", null)
                        .WithMany()
                        .HasForeignKey("ActivityModalityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_activity_modality_types_activity_modality_type_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_events_event_id");

                    b.HasOne("CodigoActivo.Domain.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activities_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activities_users_updated_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.ActivityRoleCapacity", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Activities.Activity", null)
                        .WithMany("RoleCapacities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_role_capacities_activities_activity_id");

                    b.HasOne("CodigoActivo.Domain.Activities.ActivityRoleType", null)
                        .WithMany()
                        .HasForeignKey("ActivityRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_role_capacities_activity_role_types_activity_role_");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.Assignment", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Activities.Activity", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_activities_activity_id");

                    b.HasOne("CodigoActivo.Domain.Activities.ActivityRoleType", null)
                        .WithMany()
                        .HasForeignKey("ActivityRoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_activity_role_types_activity_role_type_id");

                    b.HasOne("CodigoActivo.Domain.Activities.AssignmentStatusType", null)
                        .WithMany()
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_assignment_status_types_assignment_status_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_users_user_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.Event", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_users_updated_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventCategory", b =>
                {
                    b.HasOne("CodigoActivo.Domain.EventCategories.EventCategoryType", null)
                        .WithMany()
                        .HasForeignKey("EventCategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_event_category_types_event_category_type_id");

                    b.HasOne("CodigoActivo.Domain.Events.Event", null)
                        .WithMany("Categories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_categories_events_event_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventRating", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_ratings_events_event_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventTermsAcceptance", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_terms_acceptances_events_event_id");

                    b.HasOne("CodigoActivo.Domain.TermsDocuments.TermsDocument", null)
                        .WithMany()
                        .HasForeignKey("TermsDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_terms_acceptances_terms_documents_terms_document_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_terms_acceptances_users_user_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.EventTermsDocument", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Events.Event", null)
                        .WithMany("TermsDocuments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_terms_documents_events_event_id");

                    b.HasOne("CodigoActivo.Domain.TermsDocuments.TermsDocument", null)
                        .WithMany()
                        .HasForeignKey("TermsDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_terms_documents_terms_documents_terms_document_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Files.StoredFile", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_users_uploaded_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.News.NewsItem", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_news_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_news_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_news_users_updated_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Partners.Partner", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_partners_users_updated_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Resources.Resource", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_users_created_by");

                    b.HasOne("CodigoActivo.Domain.Resources.ResourceType", null)
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_resource_types_resource_type_id");

                    b.HasOne("CodigoActivo.Domain.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_files_thumbnail_id");

                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resources_users_updated_by");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.User", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_users_users_parent_id");

                    b.HasOne("CodigoActivo.Domain.Users.UserStatusType", null)
                        .WithMany()
                        .HasForeignKey("UserStatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_status_types_user_status_type_id");

                    b.HasOne("CodigoActivo.Domain.Users.UserType", null)
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_types_user_type_id");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Users.UserSession", b =>
                {
                    b.HasOne("CodigoActivo.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxContentPart", b =>
                {
                    b.HasOne("CodigoActivo.Infrastructure.Communication.EmailOutboxContent", "Content")
                        .WithMany("Parts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_outbox_content_parts_email_outbox_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxMessage", b =>
                {
                    b.HasOne("CodigoActivo.Infrastructure.Communication.EmailOutboxContent", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_outbox_messages_email_outbox_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Activities.Activity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RoleCapacities");
                });

            modelBuilder.Entity("CodigoActivo.Domain.Events.Event", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("TermsDocuments");
                });

            modelBuilder.Entity("CodigoActivo.Infrastructure.Communication.EmailOutboxContent", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
