export type { LearningResource } from './model/types'
export { useResourceDetail, useResources } from './api/queries'
export { resourceQueryKeys } from './api/query-keys'
export { getResourceByIdRequest, getResourcesRequest } from './api/requests'
export { default as ResourceCard } from './ui/ResourceCard.vue'
