<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="files\**" />
    <Content Remove="files\**" />
    <EmbeddedResource Remove="files\**" />
    <None Remove="files\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodigoActivo.Composition\CodigoActivo.Composition.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CodigoActivo.IntegrationTests" />
  </ItemGroup>
</Project>
